Collapsible markdown
cybertec-postgresql/today-i-learned-content pull request #20
Opened 2019-09-09 13:19 UTC by KieranKaelin

2019-09-09 13:33 UTC, LorenzHenk approved these changes

2019-09-09 13:49 UTC, PhilipTrauner requested changes
Capitalize *Markdown* and notes about feature availability.

2019-09-09 13:49 UTC, PhilipTrauner commented on posts/TEMPLATE/index.md
> +When presenting code or logs in your markdown, things tend to get out of hand quickly. \
```suggestion
When presenting code or logs in Markdown, things tend to get out of hand quickly. \
```

2019-09-09 13:49 UTC, PhilipTrauner commented on posts/TEMPLATE/index.md
> +To mitigate this, you can use collapsible markdown to hide certain parts of your document.
```suggestion
The `<details>` and `<summary>` HTML tags can be used to mitigate this, which hide certain parts of your document. Be aware, that Markdown specific syntax constructs within those HTML tags are only guaranteed to be rendered correctly by [CommonMark](https://spec.commonmark.org/0.29/#html-block) and / or [GFM](https://github.github.com/gfm/) compliant parsers (for example the GitHub Markdown parser).  
```

2019-09-09 13:49 UTC, PhilipTrauner commented on posts/TEMPLATE/index.md
> +This markdown creates the following result:
```suggestion
This Markdown creates the following result:
```

2019-09-09 13:49 UTC, PhilipTrauner commented on posts/TEMPLATE/index.md
> +title: Collapsible markdown
```suggestion
title: Collapsible Markdown
```

2019-09-09 13:49 UTC, PhilipTrauner commented on posts/TEMPLATE/index.md
> +description: "A short example on how to create collapsible markdown" # max. 300 chars.
```suggestion
description: "A short example on how to create collapsible Markdown" # max. 300 chars.
```

2019-09-11 11:29 UTC, PhilipTrauner approved these changes

2019-09-11 12:01 UTC, merged