Pretty css hack to debug layouts
cybertec-postgresql/today-i-learned-content pull request #23
Opened 2019-09-10 00:38 UTC by agustin107

2019-09-10 06:59 UTC, KieranKaelin requested changes

2019-09-10 06:59 UTC, KieranKaelin commented on posts/TEMPLATE/index.md
> +P.s: Tested on Chrome and Firefox.
```suggestion
P.S.: Tested on Chrome and Firefox.
```

2019-09-10 08:30 UTC, LorenzHenk requested changes
You did not use `git lfs` for your image!
Install `git-lfs` and follow [this guide](https://github.com/git-lfs/git-lfs/wiki/Tutorial#migrating-existing-repository-data-to-lfs) to migrate the image from git to git-lfs.
Please request a re-review when you finished.

2019-09-10 08:30 UTC, LorenzHenk commented on posts/TEMPLATE/index.md
> +tags: ["css", "hack", "debug-layout"] # max. 10 tags; lowercase; dash-separated
```suggestion
tags: ["css", "hack", "debug", "layout"] # max. 10 tags; lowercase; dash-separated
```

2019-09-10 08:30 UTC, LorenzHenk commented on posts/TEMPLATE/index.md
> +description: "Quick screenshots of your layouts to see if everything it's OK" # max. 300 chars.
```suggestion
description: "Bookmark to temporarily visualize layout of a website" # max. 300 chars.
```

2019-09-10 08:30 UTC, LorenzHenk commented on posts/TEMPLATE/index.md
> +2. Add the name that you want.
```suggestion
```

2019-09-10 08:30 UTC, LorenzHenk commented on posts/TEMPLATE/index.md
> +1. Go to add a new Bookmark in your browser.
```suggestion
1. Create a new bookmark
```

2019-09-10 08:30 UTC, LorenzHenk commented on posts/TEMPLATE/index.md
> +3. On location/URL field add this code:
```suggestion
2. Add the following code to the bookmark URL:
```

2019-09-10 08:30 UTC, LorenzHenk commented on posts/TEMPLATE/index.md
> +4. Save.
```suggestion
```

2019-09-10 08:30 UTC, LorenzHenk commented on posts/TEMPLATE/index.md
> +Is it cool no? :)
```suggestion
Ain't that cool? 😀
```

2019-09-10 08:30 UTC, LorenzHenk commented on posts/TEMPLATE/index.md
> +To see how it's works, you just to click on the bookmark name that you defined, and see you the magic!
```suggestion
To use it, just navigate to a website and click on the bookmark you defined.
The image below shows [this website](https://www.cybertec-postgresql.com/en/) with the bookmark activated.
```

2019-09-10 14:26 UTC, LorenzHenk approved these changes

2019-09-11 11:21 UTC, KieranKaelin approved these changes

2019-09-17 12:01 UTC, merged