Html base element
cybertec-postgresql/today-i-learned-content pull request #36
Opened 2019-09-18 13:25 UTC by Lana8Lee

2019-09-19 07:45 UTC, LorenzHenk requested changes
Minor improvements

2019-09-19 07:45 UTC, LorenzHenk commented on posts/TEMPLATE/index.md
> +Now **all** links will open in a new tab!
```suggestion
Now **all** links will open in a new tab by default.
```

2019-09-19 07:45 UTC, LorenzHenk commented on posts/TEMPLATE/index.md
> +Additionally, `href` attribute can be set within `<base>` tag. The base URL to be used throughout the document for relative URL addresses.
```suggestion
Additionally, the `href` attribute can be set within `<base>` tag. This sets the base URL to be used throughout the document for relative URL addresses.
```

2019-09-19 07:45 UTC, LorenzHenk commented on posts/TEMPLATE/index.md
> +... and link with an anchor in the document:
```suggestion
The following link:
```

2019-09-19 07:45 UTC, LorenzHenk commented on posts/TEMPLATE/index.md
> +...eventually, link will point to:
```suggestion
Will actually point to
```

2019-09-19 07:45 UTC, LorenzHenk commented on posts/TEMPLATE/index.md
> +tags: ["html", "html document metadata", "reference"] # max. 10 tags; lowercase; dash-separated
```suggestion
tags: ["html", "base", "document", "metadata", "reference"] # max. 10 tags; lowercase; dash-separated
```

2019-09-19 07:45 UTC, LorenzHenk commented on posts/TEMPLATE/index.md
> +title: "The Document Base element"
```suggestion
title: "The HTML Base element"
```

2019-09-19 08:34 UTC, LorenzHenk approved these changes

2019-09-20 06:08 UTC, Sascha8a approved these changes

2019-09-20 12:01 UTC, merged