git switch and git restore commans
cybertec-postgresql/today-i-learned-content pull request #70
Opened 2019-12-19 13:33 UTC by pashagolub

2019-12-19 13:43 UTC, PhilipTrauner requested changes

2019-12-19 13:43 UTC, PhilipTrauner commented on posts/TEMPLATE/index.md
> +For a long time, I was working with SVN as my default version control system. I liked it a lot for clear syntax.
```suggestion
For a long time, I was working with SVN as my default version control system. I liked it a lot for its clear syntax.
```

2019-12-19 13:43 UTC, PhilipTrauner commented on posts/TEMPLATE/index.md
> +When I switched to the git, I was surprised how `git checkout` command is overloaded.
```suggestion
When I switched to the git, I was surprised how overloaded the `checkout` sub-command really is:
```

2019-12-19 13:43 UTC, PhilipTrauner commented on posts/TEMPLATE/index.md
> +— You need to revert modifications made to the files? Use `git checkout`.
```suggestion
— You need to revert modifications made to files? Use `git checkout`. 
```

2019-12-19 13:43 UTC, PhilipTrauner commented on posts/TEMPLATE/index.md
> +Now starting from git 2.23 we have new official commands:
```suggestion
Starting with git 2.23 we have new sub-commands to address this:
```

2019-12-19 13:43 UTC, PhilipTrauner commented on posts/TEMPLATE/index.md
> +description: "Since git 2.23 git has new commands: git switch and git restore. They might help migrate from SVN" # max. 300 chars.
```suggestion
description: "git 2.23 introduces new commands: switch and restore. They might help aid migration efforts from SVN" # max. 300 chars.
```

2020-07-07 13:52 UTC, PhilipTrauner approved these changes

2020-07-07 16:08 UTC, Sascha8a approved these changes

2020-07-08 12:05 UTC, merged